antora:
  extensions:
  - require: ./..
    config_file: ./antora-navigator.yml
site:
  title: Cybersecurity stream
  start_page: cybersecurity::index.adoc
  url: https://cybersecuritystream.github.io
content:
  edit_url: ~
  sources:
  - url: https://github.com/cybersecuritystream/cybersecuritystream.github.io.git
    branches: HEAD
    start_path: docs
  - url: https://github.com/LimberDuck/antora-limberduck.git
    branches: HEAD

ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
    icons: font