site_name: Cybersecurity Stream
site_url: https://cybersecuritystream.github.io
repo_url: https://github.com/cybersecuritystream/cybersecuritystream.github.io
edit_uri: edit/main/docs/
repo_name: cybersecuritystream.github.io

theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: orange
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: orange
      accent: deep orange
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  name: material
  language: en
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
      repo: fontawesome/brands/github
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - announce.dismiss
    - navigation.indexes
    - content.code.copy
    - content.tooltips
    # - content.action.view

plugins:
  - search
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      timezone: Europe/Warsaw
      locale: en
      fallback_to_build_date: false
  - table-reader
  - social
  - blog:
      enabled: true
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: http://github.com/cybersecuritystream
      name: Cybersecurity Stream at GitHub
  status:
    new: New
    inprogress: In progress


copyright: Copyright &copy; 2017 - 2025 Cybersecurity Stream

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: '#'
      permalink_title: Direct link to this section
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - javascripts/chart.min.js
  - javascripts/chart-all.js
  - javascripts/chart-2025.js
  - javascripts/chart-2024.js
  - javascripts/chart-2023.js
  - javascripts/chart-2022.js
  - javascripts/chart-2021.js
  - javascripts/chart-2019.js

extra_css:
  - stylesheets/extra.css

watch:
  - includes

nav:
- Home: index.md
- CRC:
  - crc/index.md
  - crc/2025/index.md
  - crc/instruction/index.md
  - crc/faq.md
  - Previous editions:
    - crc/previous/index.md
    - crc/2024/index.md
    - crc/2023/index.md
    - crc/2022/index.md
    - crc/2021/index.md
    - crc/2019/index.md
    - crc/2018/index.md
    - crc/2017/index.md
- Projects & Initiatives: projects-initiatives/index.md
- Blog:
  - blog/index.md