authors:
  damiankrawczyk:
    name: Damian Krawczyk
    description: Coordinator
    avatar: https://avatars.githubusercontent.com/u/9287709?v=4
    url: https://damiankrawczyk.com
  lukaszjankowski:
    name: Łukasz Jankowski
    description: Coordinator
    avatar: https://avatars.githubusercontent.com/u/83634348?v=4
    url: https://www.linkedin.com/in/lukasz-jan-jankowski