= Corporate Readiness Certificate
:navtitle: CRC
:icons: font

image::https://avatars.githubusercontent.com/u/83579804[CRC logo, 250, float="left"]

The Corporate Readiness Certificate is an educational program launched in 2014.

Companies operating in the Silesian region in Poland implemented this program in close cooperation with the academic community and Universities. Cooperating companies deal with broadly understood services of the IT industry.

The CRC program offers active students who are open to acquiring new knowledge and practical skills, which provides unique opportunities for professional development.
The CRC program gives the possibility to gain additional specialist knowledge in IT and work management systems in large enterprises, learn about new areas of business activity, and increase the chances of participants on the labor market!

https://euslugi.polsl.pl/Formularz/Formularz/Wypelnij/70[kbd:[Detailed description of the CRC program]]

== Business partners
- https://www.accenture.com[Accenture],
- https://www.ey.com[EY],
- https://www.kyndryl.com[Kyndryl],
- https://inghubspoland.com/en[ING Hubs Poland]

== Social media

If you want to know more or don't want to miss next year's edition, follow the business partners and social media pages of the CRC education program:

* https://www.linkedin.com/company/corporate-readiness-certificate[CRC profile at LinkedIn] icon:linkedin[1x,role=black]
* https://www.instagram.com/program_crc/[CRC profile at Instagram] icon:instagram[set=fa,size=60em]
* https://m.facebook.com/ProgramCRC/[CRC profile at Facebook] icon:facebook[1x,role=black]
